### ISSUE TITLE
HL-7 Project details and technologies

### ISSUE THREAD

**Issue by sergiy2303** [sergiy2303/hardlib#10]
**_1 Upvote**_ This project is library, and we will need to store some data (books or images).
1) Need to store somewhere files and images. Something like AWS S3 free analog. For example, it can be SmartFiles.
2) Every user can upload books. Uploading should be in popular formats. File size limit: 30 Mb
3) Every book have some category.
4) Need to improve search system.
5) Need to create simple version of site, for e-books.
6) Every user can read book on site. We can use some gem for this, something like pdfjs.
7) Every user can download books.

**Comment by galulex** [comment]
[cloudinary.com](http://cloudinary.com)

**Comment by sergiy2303** [comment]
**NOTE:**
For storing files probably google drive api can be used.
https://developers.google.com/drive/v3/web/quickstart/ruby
Need to check this.
